dist: focal
language: node_js
node_js:
  - "18"

addons:
  chrome: stable

services:
  - xvfb

install:
  - npm install

before_script:
  - chmod +x node_modules/.bin/nightwatch

script:
  - npx nightwatch --env chrome tests/engineperformance.js
