dist: focal
language: node_js
node_js:
  - "18"

addons:
  chrome: stable

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sudo systemctl start xvfb
  - ls -l node_modules/.bin/
  - chmod +x node_modules/.bin/nightwatch

script:
  - npx nightwatch --env chrome tests/engineperformance.js
