language: node_js
node_js:
  - "18"

addons:
  chrome: stable   # Chrome installieren

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - ./node_modules/.bin/nightwatch --env chrome tests/engineperformance.js
