language: node_js
node_js:
  - "18"

addons:
  chrome: stable # Chrome installieren

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sudo systemctl start xvfb
  - which chromedriver
  - chromedriver --version

script:
  - npx nightwatch --env chrome tests/engineperformance.js
