language: node_js
node_js:
  - "18"

dist: focal        # Moderne Ubuntu-Version verwenden!

addons:
  chrome: stable   # Chrome installieren

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
  - sleep 3
  - chmod +x ./node_modules/.bin/nightwatch

script:
  - ./node_modules/.bin/nightwatch --env chrome tests/engineperformance.js
